name: Updec CI/CD

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file scripts/env_workflows.yaml --name base
    - name: Install Updec & Pytest
      run: |
        python setup.py develop && conda install pytest
    - name: Run differential operators test
      run: |
        cd updec/tests && pytest -q operators.py
    - name: Run cloud interpolation test
      run: |
        pytest -q updec/tests/interpolation.py
    - name: Run outward normals test
      run: |
        pytest -q updec/tests/normals.py

